Azure/terraform-provider-azapi

internal/clients/resource_client.go, internal/services/azurerm_generic_resource.go
* fix plan error when body refers to another resource
=> * fix delete error when receive 202

internal/services/azurerm_generic_resource.go, internal/services/azurerm_generic_resource_test.go, website/docs/r/azurerm-restapi_resource.html.markdown
remove create_method, update_method
=> remove create_method, update_method

go.mod, internal/services/azurerm_generic_resource.go, vendor/modules.txt, website/docs/r/azurerm-restapi_resource.html.markdown
add "schema_validation_enabled" && add validation prevent setting same property in both hcl and body
=> add "schema_validation_enabled" && add validation prevent setting same property in both hcl and body

internal/acceptance/testcase.go, internal/services/azurerm_generic_data_source_test.go, internal/services/azurerm_generic_patch_resource.go, internal/services/azurerm_generic_patch_resource_test.go, utils/helper_test.go, website/docs/r/azurerm-restapi_patch_resource.html.markdown
address https://github.com/Azure/terraform-provider-azurerm-restapi/issues/32
=> support parent_id and name in patch resource

internal/azure/location/location.go, internal/features/user_flags.go, internal/provider/provider.go, internal/services/azurerm_generic_resource.go, internal/services/azurerm_generic_resource_test.go
support default location in provider block
=> support default location in provider block

internal/services/azurerm_generic_data_source.go, internal/services/azurerm_generic_patch_resource.go, internal/services/azurerm_generic_resource.go, internal/services/resource.go, utils/helper.go, utils/helper_test.go, website/docs/index.html.markdown
https://github.com/Azure/terraform-provider-azurerm-restapi/issues/35
=> validation on `parent_id`

internal/provider/provider.go, utils/helper.go, website/docs/index.html.markdown
https://github.com/Azure/terraform-provider-azurerm-restapi/issues/44
=> Support `auxiliary_tenant_ids` in provider block

internal/azure/types/object_type.go, internal/azure/validator_test.go
https://github.com/Azure/terraform-provider-azurerm-restapi/issues/46
=> bugfix: failed to patch on a resource with user assigned identities

internal/acceptance/steps.go, internal/services/azurerm_generic_data_source.go, internal/services/azurerm_generic_data_source_test.go, internal/services/azurerm_generic_patch_resource.go, internal/services/azurerm_generic_patch_resource_test.go, internal/services/azurerm_generic_resource.go, internal/services/azurerm_generic_resource_test.go, internal/services/parse/resource.go, internal/services/parse/resource_test.go, website/docs/d/azurerm-restapi_resource.html.markdown, website/docs/r/azurerm-restapi_resource.html.markdown
to address https://github.com/Azure/terraform-provider-azurerm-restapi/issues/48
=> remove `resource_id`

internal/features/user_flags.go, internal/provider/provider.go, internal/services/azurerm_generic_patch_resource.go, internal/services/azurerm_generic_resource.go, internal/services/azurerm_generic_resource_test.go, utils/json.go, utils/json_test.go, website/docs/index.html.markdown, website/docs/r/azurerm-restapi_patch_resource.html.markdown, website/docs/r/azurerm-restapi_resource.html.markdown
https://github.com/Azure/terraform-provider-azurerm-restapi/issues/37
=> add flag to ignore missing property and incorrect casing

go.mod, internal/clients/client.go, internal/clients/correlation_id.go, internal/clients/correlation_id_test.go, vendor/modules.txt
To address: https://github.com/Azure/terraform-provider-azapi/issues/60
=> add support for correlation id header

examples/Microsoft.Management/hierarchySettings/main.tf
Add an example of how to manage management group hierarchy settings using this provider.
Note: I have already created a module to simplify this here:
https://github.com/matt-FFFFFF/terraform-azapi-mg-hierarchysettings
=> Add example hierarchy settings

internal/clients/correlation_id.go, internal/provider/provider.go
=> bugfix: long user agent is cut to 24 chars

internal/clients/client.go, internal/clients/user_agent.go, internal/provider/provider.go
To address: https://github.com/Azure/terraform-provider-azapi/issues/83
=> add more info to user agent

internal/provider/provider.go
=> remove duplicated terraform user agent

examples/Microsoft.App/containerApps/main.tf
To address https://github.com/Azure/terraform-provider-azapi/issues/100 and https://github.com/Azure/terraform-provider-azapi/issues/103
=> add example for container app

examples/Microsoft.App/containerApps/main.tf, examples/Microsoft.App/daprComponent/main.tf
To address issue: https://github.com/Azure/terraform-provider-azapi/issues/106
Many thanks to @piizei for figuring out how to use `Microsoft.ContainerRegistry/registries/taskRuns` to upload image to container registry. So, I can replace az cli scripts with azapi resource now. 🎉 
https://github.com/piizei/terraform-container-apps/blob/main/terraform/acr.tf#L32
=> add example for Microsoft.App/managedEnvironments/daprComponents

internal/azure/types/object_type.go, utils/json.go
To address https://github.com/Azure/terraform-provider-azapi/issues/109
=> bugfix: additional property is the map's value type

internal/azure/types/discriminated_object_type.go, internal/services/azapi_update_resource_test.go
address issue: https://github.com/Azure/terraform-provider-azapi/issues/112
=> add fall back when discriminated type is not in the embedded schema

docs/resources/azapi_resource.md, internal/acceptance/steps.go, internal/services/azapi_resource.go, internal/services/azapi_resource_test.go
To address: https://github.com/Azure/terraform-provider-azapi/issues/119
=> support default api-version when import azapi_resource

internal/clients/client.go, internal/provider/provider.go
Client initialization option set cloud config to support clouds othre than public.
=> Client initialization option set cloud config

CHANGELOG.md, docs/data-sources/azapi_operation.md, docs/resources/azapi_operation.md, internal/clients/resource_client.go, internal/provider/provider.go, internal/services/azapi_operation_data_source.go, internal/services/azapi_operation_data_source_test.go, internal/services/azapi_operation_resource.go, internal/services/azapi_operation_resource_test.go, internal/services/azapi_resource_test.go, internal/services/parse/resource.go
To address: https://github.com/Azure/terraform-provider-azapi/issues/57
=> new resource `azapi_opration`

examples/Microsoft.Automation/trigger_jobs/main.tf
Add `azapi_resource_action` example to add automation account job
https://github.com/Azure/terraform-provider-azapi/issues/165
=> add example for automation job

CHANGELOG.md, docs/resources/azapi_resource_action.md, internal/services/azapi_resource_action_resource.go
Fixes https://github.com/Azure/terraform-provider-azapi/issues/178
=> `azapi_resource_action` - `locks`

examples/Microsoft.DataFactory/integrationRuntimes/Airflow/main.tf
With this PR I fix the Managed Airflow IntegrationRuntime template. 
- The airflow version was not correctly specified
- I added the other airflow properties
- I updated the version to the latest version
=> Fix ADF Managed Airflow template

CHANGELOG.md, internal/services/parse/resource.go, internal/services/parse/resource_test.go
linked https://github.com/Azure/terraform-provider-azapi/issues/311
=> bugfix that tenant resource id is not parsed correctly

CHANGELOG.md, docs/data-sources/azapi_resource_list.md, internal/clients/client.go, internal/clients/resource_client.go, internal/provider/provider.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_resource_list_data_source_test.go, internal/services/parse/resource.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/313
=> new data source: `azapi_resource_list`

CHANGELOG.md, docs/resources/azapi_resource.md, docs/resources/azapi_update_resource.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_test.go, internal/services/azapi_update_resource.go, internal/services/azapi_update_resource_test.go, internal/services/resource.go, utils/json.go, utils/json_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/315
=> support for the `ignore_changes` feature

CHANGELOG.md, docs/data-sources/azapi_resource_id.md, internal/provider/provider.go, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_data_source_test.go, internal/services/azapi_resource_id_data_source.go, internal/services/azapi_resource_id_data_source_test.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_resource_list_data_source_test.go, internal/services/azapi_update_resource.go, internal/services/parse/resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/254
=> new data source: `azapi_resource_id`

CHANGELOG.md, internal/clients/client.go, internal/clients/live_traffic_log_policy.go
Add a new logger to record the traffic in a structured way, so it would be much easier to parse the traffic from the logs.
=> add a live traffic logger

CHANGELOG.md, docs/index.md, internal/provider/provider.go
This PR makes azapi provider to support customized endpoint like login endpoint, resource manager endpoint
=> `azapi` provider supports `endpoint`

docs/resources/azapi_resource_action.md, internal/acceptance/testcase.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_action_resource_test.go
Implements `when` property for `azapi_resource_action`
fixes #314
=> feat: support for `when` on resource_action

.github/workflows/acc-test.yaml, .github/workflows/depscheck.yaml, .github/workflows/golint.yaml, .github/workflows/tflint.yaml, .github/workflows/thirty-two-bit.yaml, .github/workflows/unit-test.yaml, CHANGELOG.md, internal/azure/types/object_type.go, internal/azure/validator_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/417
=> bugfix: `azapi_resource` removes some required fields in the `body` when using `ignore_body_changes` feature

go.mod, go.sum, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_id_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_update_resource.go, vendor/github.com/hashicorp/terraform-plugin-framework-timeouts/LICENSE, vendor/github.com/hashicorp/terraform-plugin-framework-timeouts/internal/validators/timeduration.go, vendor/github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts/schema.go, vendor/github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts/timeouts.go, vendor/modules.txt
After migrating to terraform-plugin-framework, providers must implement the timeouts block.
https://developer.hashicorp.com/terraform/plugin/framework/resources/timeouts
=> `azapi_*` - support `timeouts` block

.azdo/build-release-pipeline.yml
fixes https://github.com/Azure/terraform-provider-azapi/issues/233
=> add pipeline for both build and release

utils/json.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/430
=> bugfix: `ignore_body_changes` could not ignore an entire struct

CHANGELOG.md, internal/clients/resource_client.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/440
=> bugfix: `azapi_resource_action` doesn't support 204 status code

CHANGELOG.md, docs/resources/azapi_data_plane_resource.md, internal/services/parse/data_plane_type_map.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/439
=> `azapi_data_plane_resource`: support `Microsoft.Synapse/workspaces/databases` type

CHANGELOG.md, docs/index.md, internal/provider/provider.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/435
=> `azapi`: Support `client_id_file_path` and `client_secret_file_path` fields

CHANGELOG.md, internal/azure/tags/tags.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/470
=> bugfix: `azapi_resource` cannot handle tags with unknown values

CHANGELOG.md, internal/provider/provider.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/478 and https://github.com/Azure/terraform-provider-azapi/issues/475
=> bugfix: client certificate authentication doesn't work

CHANGELOG.md, internal/azure/types/discriminated_object_type.go, internal/azure/types/object_type.go, internal/azure/validator_test.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/483#issuecomment-2079029642
=> bugfix: required fields with null value failed to pass validation

CHANGELOG.md, internal/acceptance/testcase.go, internal/azure/types/string_type.go, internal/services/azapi_resource_test.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/497
=> bugfix: fix validation for unknown string value

CHANGELOG.md, internal/services/parse/resource.go, internal/services/parse/resource_test.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/494
=> `azapi_update_resource`: improve id build logic to honor user input

docs/data-sources/azapi_resource.md, docs/data-sources/azapi_resource_action.md, docs/data-sources/azapi_resource_list.md, docs/resources/azapi_data_plane_resource.md, docs/resources/azapi_resource.md, docs/resources/azapi_resource_action.md, docs/resources/azapi_update_resource.md
fixes https://github.com/Azure/terraform-provider-azapi/issues/519
=> `azapi_*` - update documents for `output` field

CHANGELOG.md, internal/services/parse/resource.go, internal/services/parse/resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/523
=> bugfix: extension resource could be applied to any scope

CHANGELOG.md, internal/provider/auth_oidc.go, internal/provider/provider.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/534
=> bugfix: oidc should not be used when required fields are missing

CHANGELOG.md, utils/json_test.go
The https://github.com/Azure/terraform-provider-azapi/pull/546 fixes a bug, and this PR adds one more test case which is mentioned in https://github.com/Azure/terraform-provider-azapi/issues/552
=> add test case for inconsistent ordering response

internal/clients/account.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/566
=> fix crash when no default subscription ID configured in az cli

docs/data-sources/resource.md, docs/data-sources/resource_action.md, docs/data-sources/resource_list.md, docs/resources/resource.md, docs/resources/resource_action.md, docs/resources/update_resource.md
add generated docs for https://github.com/Azure/terraform-provider-azapi/pull/392
=> update docs for retry feature

CHANGELOG.md, docs/index.md, internal/provider/provider.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/377， https://github.com/Azure/terraform-provider-azapi/issues/551
=> `use_msi` defaults to false

CHANGELOG.md, docs/resources/data_plane_resource.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_data_plane_resource_test.go, internal/services/migration/azapi_data_plane_resource_migration_v0_to_v2.go, internal/services/migration/azapi_data_plane_resource_migration_v1_to_v2.go
=> `azapi_data_plane_resource`: support `replace_triggers_external_values` field

internal/services/azapi_resource_test.go
Previously, I removed azurerm provider from this test. But the key vault still requires azurerm_client_config to manage the access policy, so I reverted the changes.
=> fix TestAccGenericResource_nullLocation test

docs/guides/2.0-upgrade-guide.md, templates/guides/2.0-upgrade-guide.md
The `2.0-upgrade-guide` in the `doc` folder is synced from the one in the `templates`. The two files have same contents.
=> add 2.0 upgrade guide

docs/resources/data_plane_resource.md, internal/services/parse/data_plane_type_map.go, templates/resources/data_plane_resource.md.tmpl
Fixes https://github.com/Azure/terraform-provider-azapi/issues/614
=> `azapi_data_plane_resource`: support `Microsoft.Purview/accounts/Scanning/managedvirtualnetworks` type

CHANGELOG.md
fixes https://github.com/Azure/terraform-provider-azapi/issues/623
=> Update CHANGELOG.md to fix a typo

internal/services/myvalidator/dynamic_is_not_string_validator.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/645
=> add document link in the error message

examples/Microsoft.Impact_connectors@2024-05-01-preview/main.tf, examples/Microsoft.Impact_workloadImpacts@2023-12-01-preview/main.tf
tests
```
=== RUN   TestAccExamples
--- PASS: TestAccExamples (0.01s)
=== RUN   TestAccExamples/0-Microsoft.Impact_connectors@2024-05-01-preview
azapi_resource_example_test.go:23: Running example ../../examples/0-Microsoft.Impact_connectors@2024-05-01-preview
=== PAUSE TestAccExamples/0-Microsoft.Impact_connectors@2024-05-01-preview
=== CONT  TestAccExamples/0-Microsoft.Impact_connectors@2024-05-01-preview
--- PASS: TestAccExamples/0-Microsoft.Impact_connectors@2024-05-01-preview (39.02s)
PASS
=== RUN   TestAccExamples
--- PASS: TestAccExamples (0.00s)
=== RUN   TestAccExamples/0-Microsoft.Impact_workloadImpacts@2024-05-01-preview
azapi_resource_example_test.go:23: Running example ../../examples/0-Microsoft.Impact_workloadImpacts@2024-05-01-preview
=== PAUSE …
```
=> add example for `Microsoft.Impact` RP

examples/Microsoft.ContainerRegistry_registries_taskRuns@2019-06-01-preview/main.tf, examples/Microsoft.Storage_storageAccounts_blobServices_containers_immutabilityPolicies@2023-05-01/main.tf, examples/Microsoft.Storage_storageAccounts_localUsers@2021-09-01/main.tf
=> add more azapi examples

docs/guides/2.0-upgrade-guide.md, templates/guides/2.0-upgrade-guide.md
fixes https://github.com/Azure/terraform-provider-azapi/issues/715
=> fix version constraint in docs

examples/Microsoft.App_managedEnvironments_dotNetComponents@2024-10-02-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2520301231/comment.md.
=> Add new example for Microsoft.App_managedEnvironments_dotNetComponents@2024-10-02-preview

examples/Microsoft.DBforPostgreSQL_flexibleServers@2023-06-01-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2468996953/comment.md
=> Add new example for Microsoft.DBforPostgreSQL_flexibleServers@2023-06-01-preview

examples/Microsoft.DBforPostgreSQL_flexibleServers_configurations@2022-12-01/main.tf
Add support for https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2331080928/comment.md
=> Add example for Microsoft.DBforPostgreSQL_flexibleServers_configurations@2022-12-01

examples/Microsoft.DevCenter_devcenters_attachednetworks@2023-04-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2282212155/comment.md.
=> Add example for Microsoft.DevCenter_devcenters_attachednetworks@2023-04-01

examples/Microsoft.DevCenter_networkConnections@2023-04-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2238741819/comment.md.
=> Add example for Microsoft.DevCenter_networkConnections@2023-04-01

examples/Microsoft.RecoveryServices_vaults_backupconfig@2024-04-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2177912319/comment.md.
=> Add example for Microsoft.RecoveryServices_vaults_backupconfig@2024-04-01

examples/Microsoft.Communication_emailServices_domains@2023-04-01-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/git%20merge%20/comment.md.
=> Add example for Microsoft.Communication_emailServices_domains@2023-04-01-preview

examples/Microsoft.Web_sites_siteextensions@2022-09-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2138742360/comment.md.
=> Add example for Microsoft.Web_sites_siteextensions@2022-09-01

examples/Microsoft.SqlVirtualMachine_sqlVirtualMachines@2023-10-01/SQL_best_practices_assessment/main.tf, examples/Microsoft.SqlVirtualMachine_sqlVirtualMachines@2023-10-01/basic/main.tf
related issue:https://github.com/Azure/terraform-provider-azapi/issues/738
=> add example for `Microsoft.SqlVirtualMachine/sqlVirtualMachines@2023-10-01`

examples/Microsoft.DesktopVirtualization_applicationGroups_applications@2023-09-05/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/2106830118/comment.md.
=> Add example for Microsoft.DesktopVirtualization_applicationGroups_applications@2023-09-05

examples/Microsoft.Communication_emailServices_domains_senderUsernames@2023-04-01-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1829783238/comment.md.
=> Add example for Microsoft.Communication_emailServices_domains_senderUsernames@2023-04-01-preview

examples/Microsoft.Sql_servers_sqlVulnerabilityAssessments@2022-05-01-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1831935137/comment.md.
=> Add example for Microsoft.Sql_servers_sqlVulnerabilityAssessments@2022-05-01-preview

examples/Microsoft.Authorization_roleAssignments@2022-04-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1832144880/comment.md.
=> Add example for Microsoft.Authorization_roleAssignments@2022-04-01

examples/Microsoft.Sql_servers_auditingSettings@2022-05-01-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1833870854/comment.md.
=> Add example for Microsoft.Sql_servers_auditingSettings@2022-05-01-preview

examples/Microsoft.Cache_redis_accessPolicyAssignments@2023-04-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1976041452/comment.md.
=> Add example for Microsoft.Cache_redis_accessPolicyAssignments@2023-04-01

examples/Microsoft.Automation_automationAccounts_powershell72Modules@2020-01-13-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1701929433/comment.md.
=> Add example for Microsoft.Automation_automationAccounts_powershell72Modules@2020-01-13-preview

examples/Microsoft.CognitiveServices_accounts_deployments@2022-10-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1608619560/comment.md
=> Add example for Microsoft.CognitiveServices/accounts/deployments@2023-05-01

examples/Microsoft.Network_virtualHubs_routingIntent@2022-09-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1577417723/comment.md.
=> Add example for Microsoft.Network_virtualHubs_routingIntent@2022-09-01

examples/Microsoft.Web_connections@2016-06-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1702491304/comment.md.
=> Add example for Microsoft.Web_connections@2016-06-01

examples/Microsoft.Network_frontDoors_rulesEngines@2020-05-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1192409333/comment.md.
=> Add example for Microsoft.Network_frontDoors_rulesEngines@2020-05-01

examples/Microsoft.KubernetesConfiguration_fluxConfigurations@2022-11-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1227659088/comment.md.
=> Add example for Microsoft.KubernetesConfiguration_fluxConfigurations@2022-11-01

examples/Microsoft.ManagedIdentity_userAssignedIdentities_federatedIdentityCredentials@2023-01-31/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1285636875/comment.md.
=> Add example for Microsoft.ManagedIdentity_userAssignedIdentities_federatedIdentityCredentials@2023-01-31

examples/Microsoft.ApiManagement_service_policyFragments@2021-08-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1314991599/comment.md.
=> Add example for Microsoft.ApiManagement_service_policyFragments@2021-08-01

examples/Microsoft.Security_automations@2019-01-01-preview/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1334876195/comment.md.
=> Add example for Microsoft.Security_automations@2019-01-01-preview

examples/Microsoft.ApiManagement_service_templates@2021-08-01/main.tf, examples/Microsoft.ApiManagement_service_templates@2021-08-01/testdata/invite.html.tpl
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1445126743/comment.md.
=> Add example for Microsoft.ApiManagement_service_templates@2021-08-01

examples/Microsoft.Network_privateEndpoints@2022-01-01/main.tf
This PR is to support https://github.com/ms-henglu/tools/blob/main/tools/azurerm-issue-comment-searcher/examples/1509453108/comment.md.
=> Add example for Microsoft.Network/privateEndpoints@2022-01-01

examples/Microsoft.Network_virtualNetworks@2024-05-01/with_ipam_pool/main.tf, internal/services/azapi_resource_example_test.go
make example-test TARGET=Microsoft.Network_virtualNetworks@2024-05-01
TF_ACC=1 ARM_TEST_EXAMPLES=Microsoft.Network_virtualNetworks@2024-05-01 go test -v ./internal/services/... -run TestAccExamples_Selected -timeout 300m -ldflags="-X=github.com/Azure/terraform-provider-azapi/version.ProviderVersion=acc"
=== RUN   TestAccExamples_Selected
azapi_resource_example_test.go:56: Found 1 testcases
=== RUN   TestAccExamples_Selected/../../examples/Microsoft.Network_virtualNetworks@2024-05-01/with_ipam_pool/main.tf
=== PAUSE TestAccExamples_Selected/../../examples/Microsoft.Network_virtualNetworks@2024-05-01/with_ipam_pool/main.tf
=== CONT  TestAccExamples_Selected/../../examples/Microsoft.Network_virtualNetworks@2024-05-01/with_ipam_pool/main.tf
--- PASS: TestAccExamples_Selected (0.00s)
--- PASS: …
=> example - add vnet with IPAM pool in `Microsoft.Network_virtualNetworks@2024-05-01`

examples/Microsoft.Automation_automationAccounts_sourceControls@2023-11-01/main.tf, examples/Microsoft.Automation_automationAccounts_sourceControls_sourceControlSyncJobs@2023-11-01/main.tf
related issues: https://github.com/Azure/terraform-provider-azapi/issues/163
=> add examples for automation account source controls

examples/Microsoft.Storage_storageAccounts@2021-09-01/with_private_endpoint/main.tf
```
--- PASS: TestAccExamples_Selected (0.01s)
--- PASS: TestAccExamples_Selected/../../examples/Microsoft.Storage_storageAccounts@2021-09-01/basic/main.tf (63.96s)
--- PASS: TestAccExamples_Selected/../../examples/Microsoft.Storage_storageAccounts@2021-09-01/with_private_endpoint/main.tf (1265.09s)
PASS
ok      github.com/Azure/terraform-provider-azapi/internal/services     1268.086s
```
=> fix `Microsoft.Storage_storageAccounts@2021-09-01` test

examples/Microsoft.Billing_billingAccounts_billingProfiles@2024-04-01/main.tf
This PR is to add example for [Microsoft.Billing_billingAccounts_billingProfiles@2024-04-01](https://github.com/Azure/azure-rest-api-specs/blob/115eea12f7c785b58ff6499d1ad509152bb63c60/specification/billing/resource-manager/Microsoft.Billing/stable/2024-04-01/billingProfile.json#L170).
=> Add example for Billing Profile

CHANGELOG.md, examples/Qumulo.Storage_fileSystems@2024-06-19/main.tf, internal/azure/tags/tags.go, internal/azure/types/any_type.go, internal/azure/types/array_type.go, internal/azure/types/boolean_type.go, internal/azure/types/discriminated_object_type.go, internal/azure/types/integer_type.go, internal/azure/types/object_type.go, internal/azure/types/resource_function_type.go, internal/azure/types/resource_type.go, internal/azure/types/string_literal_type.go, internal/azure/types/string_type.go, internal/azure/types/type_base.go, internal/azure/types/union_type.go, internal/azure/validator_test.go, internal/services/azapi_data_plane_resource_test.go, internal/services/azapi_resource.go, internal/services/resource.go
This PR refactors the schema validation to support validation with unknown values. And moves the validation from `plan` phase to `validate` phase.
=> Ticket 32063735 schema validation

CHANGELOG.md, internal/services/azapi_resource.go, internal/services/azapi_resource_preflight_test.go, internal/services/preflight/preflight.go, internal/services/preflight/preflight_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/800
=> Preflight validation supports nested resources

docs/resources/update_resource.md
A minor grammatical fix on `docs/resources/update_resource.md`. Corresponding website page: https://registry.terraform.io/providers/Azure/azapi/latest/docs/ephemeral-resources/resource_action
=> update_resource.md: minor grammatical fix

examples/Microsoft.Sql_servers_outboundFirewallRules@2021-02-01-preview/main.tf
removed password from example replacing it with a required variable marked as secret
=> remove password from example

docs/resources/resource.md, docs/resources/update_resource.md, internal/services/azapi_resource.go
Fixes #846
Please can you review @ms-henglu
=> docs(azapi_resource): update id attribute to use correct description

examples/Microsoft.Network_networkManagers_routingConfigurations_ruleCollections_rules@2024-05-01/main.tf
=> add new example for `Microsoft.Network_networkManagers_routingConfigurations_ruleCollections_rules@2024-05-01`

docs/guides/Microsoft.Network_networkManagers_routingConfigurations_ruleCollections_rules.md, examples/Microsoft.Network_networkManagers_routingConfigurations_ruleCollections_rules@2024-05-01/main.tf
make example-test TARGET=Microsoft.Network_networkManagers_routingConfigurations_ruleCollections_rules@2024-05-01
=> example - add commit example for `Microsoft.Network_networkManagers_routingConfigurations_ruleCollections_rules@2024-05-01`

docs/guides/Microsoft.StandbyPool_standbyvirtualmachinepools.md, examples/Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01/basic/main.tf, tools/generator-example-doc/resource_providers.json, tools/generator-example-doc/resource_types.json
test:
```
❯ make example-test TARGET=Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01
TF_ACC=1 ARM_TEST_EXAMPLES=Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01 go test -v ./internal/services/... -run TestAccExamples_Selected -timeout 300m -ldflags="-X=github.com/Azure/terraform-provider-azapi/version.ProviderVersion=acc"
=== RUN   TestAccExamples_Selected
azapi_resource_example_test.go:56: Found 1 testcases
=== RUN   TestAccExamples_Selected/../../examples/Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01/basic/main.tf
=== PAUSE TestAccExamples_Selected/../../examples/Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01/basic/main.tf
=== CONT  TestAccExamples_Selected/../../examples/Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01/basic/m …
```
=> add example for `Microsoft.StandbyPool_standbyvirtualmachinepools`

docs/resources/Microsoft.Network_virtualNetworks.md, examples/Microsoft.Network_virtualNetworks@2024-05-01/with_ipam_pool/main.tf, examples/Microsoft.Network_virtualNetworks_subnets@2024-05-01/with_ipam_pool/main.tf
=> example - Microsoft.Network_virtualNetworks_subnets@2024-05-01/with_ipam_pool

docs/guides/feature_preflight.md, templates/guides/feature_preflight.md
https://github.com/Azure/terraform-provider-azapi/issues/907
=> add notice for preflight validation

docs/data-sources/client_config.md, docs/data-sources/resource.md, docs/data-sources/resource_action.md, docs/data-sources/resource_id.md, docs/data-sources/resource_list.md, docs/ephemeral-resources/resource_action.md, docs/resources/resource_action.md, internal/services/azapi_client_config_data_source.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_ephemeral.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_id_data_source.go, internal/services/azapi_resource_list_data_source.go, templates/data-sources.md.tmpl
fixes https://github.com/Azure/terraform-provider-azapi/issues/883
=> add docs for data source and resources

.azdo/ado-oidc-pipeline.yml
=> Update oidc azure pipeline test cases

CHANGELOG.md, internal/services/validate/resource_id.go, internal/services/validate/resource_id_test.go
=> improve resource id validation

CHANGELOG.md, internal/azure/types/discriminated_object_type.go, internal/services/azapi_resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/937
=> bugfix: schema validation fails when discriminator is unknown

CHANGELOG.md, internal/services/azapi_resource.go, internal/services/azapi_resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/955 https://github.com/Azure/terraform-provider-azapi/issues/917
=> azapi_resource: extend move-state derivation to storage container, key vault secret, and key

CHANGELOG.md, docs/data-sources/resource.md, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_data_source_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/131
=> `azapi_resource` data source supports `ignore_not_found` and `exists`

CHANGELOG.md, internal/clients/options.go, internal/clients/options_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/985
=> Fix panic in retry policy when HTTP response is nil
