Azure/terraform-provider-azapi

internal/services/azapi_resource.go, internal/services/azapi_update_resource.go, internal/services/parse/resource.go, internal/services/parse/resource_test.go, internal/services/resource.go, utils/helper.go, utils/helper_test.go
To address issue:
https://github.com/Azure/terraform-provider-azapi/issues/73
Add a validation to prevent user setting `parent_id = ""`, which means "/" is the only allowed value for tenant scope top level resource.
To address issue:
https://github.com/Azure/terraform-provider-azapi/issues/72
I refactored the validation logics, into two parts.
1. Child resource type: verify if the parent_id's type matches the expected resource type, for example,
resource type is `Microsoft.Network/virtualNetworks/subnets`, we need to verify whether `parent_id` is an ID of a `Microsoft.Network/virtualNetworks`
2. Top level resource type: verify if `parent_id` provides a correct scope, like tenant scope `/`, subscription scope `/subscriptions/000-000-00`
=> improve resource_id validation logics

internal/services/azapi_resource.go
This is a bugfix for an edge case, when update `azapi_resource`, identity and location defined inside body will be over-written by computed identity and location
=> bugfix: identity and location defined inside body will be over-written by computed identity and location when update

docs/guides/managed_service_identity.md
To address https://github.com/Azure/terraform-provider-azapi/issues/87
Managed identity authentication is enabled in authentication chain by default, no need to expose property `use_msi`.
ref: https://github.com/Azure/terraform-provider-azapi/blob/main/vendor/github.com/Azure/azure-sdk-for-go/sdk/azidentity/default_azure_credential.go#L42
=> remove use_msi from documents

utils/json.go
There'll be a plan-diff if user configured `some_property` to a zero value like empty string, empty array, empty map, and response omitted this property.
For example, in `Microsoft.ContainerService/managedClusters/agentPools@2022-01-02-preview`, if users want to reset `nodel_labels` to empty, users can use the following config:
```
nodeLabels = {}
```
And backend doesn't return `nodeLabels` in response, we should take this response as matched with configuration instead of diff.
=> suppress diff if zero value is configured in body and omitted in response

CHANGELOG.md, internal/acceptance/steps.go, internal/services/azapi_resource.go, internal/services/azapi_resource_test.go
When import the `azapi_resource`, `api-version` is required as a query parameter, but this id should not be stored in state directly, `api-version` should be removed.
=> fix id format in imported resource

CHANGELOG.md, internal/services/resource.go
The previous error message from schema validation failure is misleading, users might think it's a server-side error, so I added some messages suggesting how to fix it or bypass it.
=> improve error message for schema validation failure

CHANGELOG.md, internal/azure/types/discriminated_object_type.go, internal/services/azapi_update_resource.go, internal/services/azapi_update_resource_test.go, utils/helper.go
To address: https://github.com/Azure/terraform-provider-azapi/issues/112
Though the root cause is server-side bugs, but azapi provider should not crash.
=> fix crash when update on a resource whose id is null

CHANGELOG.md, docs/data-sources/azapi_resource.md, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_data_source_test.go, internal/services/azapi_update_resource.go
To address: https://github.com/Azure/terraform-provider-azapi/issues/134
`azapi_resource` data source: Supports configuring `resource_id` as an alternative way to configure `name` and `parent_id`.
=> `azapi_resource` data source supports `resource_id`

internal/provider/provider.go
To address: https://github.com/Azure/terraform-provider-azapi/issues/144
Root cause: If an invalid `AZURE_CLIENT_ID` is set, managed identity authentication will fail as its configuration has error, which is fatal, then the azure cli authentication is skipped.
refs: https://github.com/Azure/azure-sdk-for-go/issues/18352#issuecomment-1160987065
=> bugfix: do not set env if values are empty

internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_resource.go
The IDs of `azapi_resource_action` resource and data source were set to the IDs of the targeting resources, but it's better to use request path(combining action).
=> action resource's id should be the request path

internal/clients/resource_client.go, internal/services/resource.go
Fixes https://github.com/Azure/terraform-provider-azapi/issues/171
Supports `text/plain` content-type response.
=> `azapi_resource_action` supports text content-type output

CHANGELOG.md, internal/services/azapi_resource_action_resource.go
Fixed https://github.com/Azure/terraform-provider-azapi/issues/206
=> `azapi_resource_action`: The `output` should be refreshed when `body`  is changed

internal/acceptance/testcase.go, internal/services/azapi_resource_test.go, internal/services/azapi_update_resource_test.go, utils/json.go
By Azure rest API guideline, sensitive properties should be omitted in GET response, but some of them are returned in asterisks. This PR will ignore those secrets in asterisks.
=> `azapi_resource` - ignore secrets which are returned in asterisks

internal/services/azapi_resource.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_test.go, internal/services/azapi_update_resource.go
Update with wrong API version will write wrong value to state file, which leads to state refresh error in later apply.
related to https://github.com/hashicorp/terraform-plugin-sdk/issues/476
use the `partial mode`, see [doc](https://www.hashicorp.com/blog/writing-custom-terraform-providers):
> If the Update callback returns with or without an error, the full state is saved. If the ID becomes blank, the resource is destroyed (even within an update, though this shouldn't happen except in error scenarios).
> Partial mode is a mode that can be enabled by a callback that tells Terraform that it is possible for partial state to occur. When this mode is enabled, the provider must explicitly tell Terraform what is safe to persist and what is not.
```
TF_ACC=1 go test -v ./internal/services …
```
=> support `partial mode` to avoid writing diff to state while `Update` error

CHANGELOG.md, internal/services/azapi_resource.go
Fix a bug that schema validation requires redundant `name` fields boh in resource and in body
Fixes https://github.com/Azure/terraform-provider-azapi/issues/245
=> Fix a bug that schema validation requires redundant `name` fields boh in resource and in body

utils/json.go, utils/json_test.go
- Update regex match to be either stars or the literal `<redacted>`
- Resolves #268
- Included test case where plan sees key, server response shows `<redacted>`, but resulting json is still key
=> Ignore `<redacted>` in response

CHANGELOG.md, docs/index.md, internal/clients/client.go, internal/provider/provider.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/296
```hcl
provider "azapi" {
custom_correlation_request_id = "1234567890"
}
```
```
PUT https://management.azure.com/subscriptions/******/resourceGroups/henglu1114/providers/Microsoft.Automation/automationAccounts/henglu1114?api-version=2022-08-08 HTTP/2.0
content-type: application/json
user-agent: HashiCorp Terraform/1.4.5 (+https://www.terraform.io) Terraform Plugin SDK/2.8.0 terraform-provider-azapi/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
x-ms-correlation-request-id: 1234567890       <<----- here
authorization: ******
accept: application/json
content-length: 83
accept-encoding: gzip
{"location":"westeurope","name":"henglu1114","properties":{"sku":{"name":"Basic"}}}
```
=> `azapi` - `custom_correlation_request_id`

CHANGELOG.md, docs/data-sources/azapi_resource_action.md, docs/guides/frequently_asked_questions.md, docs/resources/azapi_data_plane_resource.md, docs/resources/azapi_resource_action.md, internal/services/azapi_resource_action_data_source_test.go, internal/services/azapi_resource_action_resource_test.go, internal/services/parse/resource.go, internal/services/parse/resource_test.go
related issues: https://github.com/Azure/terraform-provider-azapi/issues/299, https://github.com/Azure/terraform-provider-azapi/issues/316
This PR does the following things:
1. The `type` supports the resource provider name as the resource type for the provider IDs, for example, `Microsoft.Network`, to enable provider level actions with `azapi_resource_action` resource/data source.
2. Fix the bug that resource IDs for type  `Microsoft.Resources/providers` for provider IDs as not parsed correctly. It's used to register/unregister RP or fetch information of RPs.
```
=== RUN   TestAccActionResource_basic
=== PAUSE TestAccActionResource_basic
=== CONT  TestAccActionResource_basic
--- PASS: TestAccActionResource_basic (156.84s)
=== RUN   TestAccActionResource_registerResourceProvider
=== PAUSE …
```
=> `azapi_resource_action` - supports provider level actions

CHANGELOG.md, docs/data-sources/azapi_resource.md, docs/resources/azapi_resource.md, internal/clients/account.go, internal/clients/client.go, internal/provider/provider.go, internal/services/azapi_resource.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_data_source_test.go, internal/services/azapi_resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/322
Tests
```
=== RUN   TestAccGenericResource_defaultParentId
=== PAUSE TestAccGenericResource_defaultParentId
=== CONT  TestAccGenericResource_defaultParentId
--- PASS: TestAccGenericResource_defaultParentId (37.84s)
PASS
=== RUN   TestAccGenericDataSource_defaultParentId
=== PAUSE TestAccGenericDataSource_defaultParentId
=== CONT  TestAccGenericDataSource_defaultParentId
--- PASS: TestAccGenericDataSource_defaultParentId (44.13s)
PASS
```
=> `azapi_resource` - `parent_id` is optional for resource groups

CHANGELOG.md, internal/clients/resource_client.go, internal/services/azapi_resource_action_data_source_test.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/271, https://github.com/Azure/terraform-provider-azapi/issues/184
=> ignore polling error from nonstandard LRO APIs

internal/services/azapi_resource.go
In previous fix for issue https://github.com/Azure/terraform-provider-azapi/issues/245, PR https://github.com/Azure/terraform-provider-azapi/pull/260 adds `name` field to the `body`.
This PR only adds `name` field to the `body` in schema validation.
=> only adds `name` to `body` in schema validation

internal/services/azapi_resource.go
This PR sets a default null value for the timeouts when import the resource. If not set, a value conversion error will happen.
=> bugfix: timeout is not set when import `azapi_resource`

CHANGELOG.md, docs/data-sources/azapi_resource.md, docs/data-sources/azapi_resource_action.md, docs/data-sources/azapi_resource_list.md, docs/resources/azapi_data_plane_resource.md, docs/resources/azapi_resource.md, docs/resources/azapi_resource_action.md, docs/resources/azapi_update_resource.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_data_plane_resource_test.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_resource_test.go, internal/services/azapi_update_resource.go, internal/services/azapi_update_resource_test.go, internal/services/defaults/dynamic_default.go, internal/services/migration/azapi_data_plane_resource_migration_v0_to_v1.go, internal/services/migration/azapi_resource_action_migration_v0_to_v1.go, internal/services/migration/azapi_resource_migration_v0_to_v1.go, internal/services/migration/azapi_update_resource_migration_v0_to_v1.go, internal/services/resource.go
This PR makes the `body` and `output` fields supports dynamic schema and removes the `payload` and `output_payload` fields.
=> `azapi_*` - the `body` and `output` fields support dynamic schema

CHANGELOG.md, internal/services/azapi_update_resource_test.go, utils/json.go, utils/json_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/445
This PR ignores the order of the elements in a list if the element has a name field as identifier. It also suppress the diff of the existing items between config and remote if the array in remote has more elements.
For example:
In config:
```hcl
subnets = [
{
name = "default"
properties = {
addressPrefix = "10.0.3.0/24"
}
}
]
```
But in remote:
```hcl
subnets = [
{
"name": "default",
"id": "id2,
"etag": "W/\"d0338b06-c645-4b66-a502-3452eeca0aeb\"",
"properties": {
"provisioningState": "Succeeded",
"addressPrefix": "10.0.3.0/24",
"delegations": [],
"privateEndpointNetworkPolicies": "Disabled",
"privateLinkServiceNetworkPolicies": "Enabled"
},
"type": "Microsoft.Network/virtualNetworks/subnets"
},
{
"name": "second", …
```
=> ignore the order of the elements in a list

CHANGELOG.md, internal/azure/types/integer_type.go, internal/azure/types/string_type.go
The PR fixes the validation error like the following config:
```hcl
/*
│ embedded schema validation failed: the argument "body" is invalid:
│ `properties.distribution` is invalid, expect `string` but got `<nil>`
│ `properties.infrastructure` is invalid, expect `string` but got `<nil>`
│  You can try to update `azapi` provider to the latest version or disable the validation using the feature flag `schema_validation_enabled = false` within the resource block
*/
resource "azapi_resource" "connectedCluster" {
type = "Microsoft.Kubernetes/connectedClusters@2024-01-01"
name      = var.aksArcName
parent_id = var.resourceGroup.id
body = {
kind = "ProvisionedCluster"
properties = {
aadProfile = {
adminGroupObjectIDs = flatten(var.rbacAdminGroupObjectIds)
enableAzureRBAC     = true
tenantID …
```
=> bugfix: null value can't pass schema validation

CHANGELOG.md, internal/services/azapi_resource.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/462
In the following function, to suppress the diff of config: tags = null and state: tags = {}, it'll set plan.tags to {} even if it's not defined in config when upgrading from previous provider.
And this will fail the schema validation if the resource doesn't support "tags". And bypassing the validation won't mitigate this, because the empty tags will be set in the request body and user will get a bad request error.
The fix is adding tags to the request body only if it's not empty.
https://github.com/Azure/terraform-provider-azapi/blob/192e61be293b5e71814063e57c96ca7dd7e5024c/internal/services/azapi_resource.go#L858-L880
=> bugfix: skip setting empty tags in request body

CHANGELOG.md, internal/azure/types/integer_type.go, internal/azure/validator_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/468
It's a dependency issue because it parses double as integer type. We'll skip the validation if the number is float.
=> bugfix: skip validating the float number in the body

CHANGELOG.md, docs/data-sources/azapi_resource.md, docs/data-sources/azapi_resource_action.md, docs/data-sources/azapi_resource_list.md, docs/index.md, internal/acceptance/check/that.go, internal/features/user_flags.go, internal/provider/provider.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_data_source_test.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_data_source_test.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_resource_list_data_source_test.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/467
This PR will introduce a feature flag in the provider block to control the output format for data sources. The default value is `false` which means the output format defaults to JSON for data source. And this will resolve the breaking changes in previous release.
=> `azapi`: Support `enable_hcl_output_for_data_source` field

CHANGELOG.md, internal/acceptance/steps.go, internal/acceptance/testcase.go, internal/services/azapi_data_plane_resource_test.go, internal/services/azapi_data_plane_resource_upgrade_test.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_action_resource_upgrade_test.go, internal/services/azapi_resource_test.go, internal/services/azapi_resource_upgrade_test.go, internal/services/azapi_update_resource_test.go, internal/services/azapi_update_resource_upgrade_test.go, internal/services/migration/azapi_resource_action_migration_v0_to_v1.go
This PR adds a new set of tests to detect breaking changes between the previous released provider and the developing one.
It will use the previous released provider to deploy the config, then run `terraform plan` with the developing provider to see if there's any plan diff. The expected behavior is getting no changes in the `terraform plan`.
With these tests, some potential breaking changes are detected:
1. Resource which doesn't support `location` will see a plan diff to set location to null after upgrading. (fixed in this PR)
2. Azapi resource action which doesn't have a `body` will see the body sets to `{}` after upgrading. (fixed in this PR)
3. Azapi resource action which doesn't specify `when` and upgrading from a very old provider version, will see the plan diff to add `when=apply`. …
=> add upgrade tests to detect breaking changes

CHANGELOG.md, docs/resources/azapi_data_plane_resource.md, docs/resources/azapi_resource.md, docs/resources/azapi_resource_action.md, docs/resources/azapi_update_resource.md, internal/acceptance/testcase.go, internal/services/azapi_data_plane_resource.go, internal/services/azapi_data_plane_resource_test.go, internal/services/azapi_data_plane_resource_upgrade_test.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_action_resource_upgrade_test.go, internal/services/azapi_resource_test.go, internal/services/azapi_resource_upgrade_test.go, internal/services/azapi_update_resource.go, internal/services/azapi_update_resource_test.go, internal/services/azapi_update_resource_upgrade_test.go, internal/services/migration/azapi_data_plane_resource_migration_v0_to_v1.go, internal/services/migration/azapi_resource_action_migration_v0_to_v1.go, internal/services/migration/azapi_resource_migration_v0_to_v1.go, internal/services/migration/azapi_update_resource_migration_v0_to_v1.go
This PR adds `timeouts.update` field which is removed in v1.13.x by mistake.
To avoid potential breaking changes introduced by this PR, I've added more tests:
1. Upgrade from v1.12.1 to current version, the updated migration function will update the schema from v0 to v1 correctly.
2. Upgrade from v1.13.1 to current version, the schema is already updated to v0 to v1. But in v1.13.x, the update timeout is not supported, so upgrading will have no breaking changes. And users could still be able to add update timeout after using the latest version.
=> `azapi_*` - support for the `timeouts.update` field

CHANGELOG.md, docs/guides/service_principal_client_certificate.md, docs/index.md, internal/acceptance/testcase.go, internal/provider/provider.go, internal/services/azapi_auth_test.go, internal/services/azapi_resource_test.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/488
This PR also refactors the logics that build credentials and adds test cases for different authentication methods.
Test results:
1. az cli
```
=== RUN   TestAccAuth_azcli
=== PAUSE TestAccAuth_azcli
=== CONT  TestAccAuth_azcli
--- PASS: TestAccAuth_azcli (39.17s)
PASS
```
2. sp client secret
running test....
3. sp client certificate path
```
=== RUN   TestAccAuth_clientCertificatePath
=== PAUSE TestAccAuth_clientCertificatePath
=== CONT  TestAccAuth_clientCertificatePath
--- PASS: TestAccAuth_clientCertificatePath (38.29s)
PASS
```
4. sp client certificate
```
=== RUN   TestAccAuth_clientCertificate
=== PAUSE TestAccAuth_clientCertificate
=== CONT  TestAccAuth_clientCertificate
--- PASS: …
```
=> `azapi`: Support `client_certificate` field

internal/services/azapi_resource_test.go
This PR updates the test case for extension scope resource, because the there's an Api issue on the `Microsoft.Authorization/locks` resource which make the test case intermittently failed.
=> update tests for extension scoped resource

CHANGELOG.md, docs/data-sources/azapi_client_config.md, internal/acceptance/testclient.go, internal/clients/account.go, internal/clients/client.go, internal/provider/provider.go, internal/services/azapi_client_config_data_source.go, internal/services/azapi_client_config_data_source_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/504
This PR adds an `azapi_client_config` data source which is used to get information about the configuration of azapi provider. For the first iteration, it only supports `subscription_id` and `tenant_id`.
This data source will try to retrieve these information from provider's block directly, if not specified, it will try to load from az cli command.
=> new data source: `azapi_client_config`

docs/index.md, internal/provider/provider.go
Implement AKS Workload Identity in a similar way to [azurerm](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/aks_workload_identity).
Closes https://github.com/Azure/terraform-provider-azapi/issues/518
=> feat: add AKS workload identity authentication

utils/json.go, utils/json_test.go
fixes #545
`utils.UpdateObject` would duplicate array members under certain conditions.
Adds `reflect.DeepEqual()` check to start of `utils.UpdateObject` to return early if old is the same as new. This could be masking the original bug but it's still probably a worthy thing to do.
This PR adds a test, which used to fail but now passes.
Pinging @ms-henglu
=> fix: `utils.UpdateObject` duplication of array members

CHANGELOG.md, internal/services/azapi_update_resource.go, internal/services/azapi_update_resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/554
=> bugfix: inconsistent results when the case of `resource_id` and `type` are different

CHANGELOG.md, docs/data-sources/azapi_resource.md, docs/data-sources/azapi_resource_action.md, docs/data-sources/azapi_resource_list.md, docs/index.md, docs/resources/azapi_resource.md, internal/features/user_flags.go, internal/provider/provider.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_data_source_test.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_data_source_test.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_resource_list_data_source_test.go, internal/services/azapi_resource_test.go
This PR adds the following breaking changes in 2.0 beta:
- Provider field `default_naming_prefix` and `default_naming_suffix` are removed. Please specify the naming prefix and suffix in the resource's `name` field instead.
- Provider field `enable_hcl_output_for_data_source` is removed. The `output` field in the data source is always in HCL format.
- The `azapi_resource`'s `removing_special_chars` field is removed. Please specify the `name` field and remove the special characters in the `name` field instead.
=> Branch 240807 deprecate features

CHANGELOG.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_data_plane_resource_test.go, internal/services/azapi_data_plane_resource_upgrade_test.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_action_resource_upgrade_test.go, internal/services/azapi_resource_test.go, internal/services/azapi_resource_upgrade_test.go, internal/services/azapi_update_resource.go, internal/services/azapi_update_resource_test.go, internal/services/azapi_update_resource_upgrade_test.go, internal/services/migration/azapi_data_plane_resource_migration_v0_to_v2.go, internal/services/migration/azapi_resource_action_migration_v0_to_v2.go, internal/services/migration/azapi_resource_migration_v0_to_v2.go, internal/services/migration/azapi_update_resource_migration_v0_to_v2.go
This PR updates the state migration for the v0 schema, and adds tests.
=> bugfix: state migration should target the latest schema

docs/resources/data_plane_resource.md, internal/clients/data_plane_client.go, internal/clients/data_plane_client_mock_test.go, internal/clients/data_plane_client_test.go, internal/services/azapi_data_plane_resource.go, internal/services/migration/azapi_data_plane_resource_migration_v0_to_v2.go, internal/services/migration/azapi_data_plane_resource_migration_v1_to_v2.go
This PR adds retry function to the data plane resource.
```
=== RUN   TestAccAzapiDataPlaneResourceUpgrade_appConfigKeyValues
=== PAUSE TestAccAzapiDataPlaneResourceUpgrade_appConfigKeyValues
=== CONT  TestAccAzapiDataPlaneResourceUpgrade_appConfigKeyValues
=== RUN   TestAccAzapiDataPlaneResourceUpgrade_purviewClassification
=== PAUSE TestAccAzapiDataPlaneResourceUpgrade_purviewClassification
=== CONT  TestAccAzapiDataPlaneResourceUpgrade_purviewClassification
=== RUN   TestAccAzapiDataPlaneResourceUpgrade_purviewCollection
=== PAUSE TestAccAzapiDataPlaneResourceUpgrade_purviewCollection
=== CONT  TestAccAzapiDataPlaneResourceUpgrade_purviewCollection
=== RUN   TestAccAzapiDataPlaneResourceUpgrade_keyVaultIssuer
=== PAUSE TestAccAzapiDataPlaneResourceUpgrade_keyVaultIssuer
=== CONT …
```
=> `azapi_data_plane_resource`: support `retry` field

internal/services/azapi_resource.go
Hi @ms-henglu 
In testing I found a scenario where we want to add a retryable error for a ResourceNotFound situation. For new resources, there is a check to ensure the resource does not already exist. If we use the retry client then the provider will infinite loop until the context deadline.
This fix ensures we use the non-retry client to check that the resource does not already exist!
=> fix: always use non-retry client to check new resource does not exist

internal/acceptance/testcase.go, internal/services/azapi_data_plane_resource.go, internal/services/azapi_data_plane_resource_test.go, internal/services/azapi_data_plane_resource_upgrade_test.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source_test.go, internal/services/azapi_resource_action_resource_test.go, internal/services/azapi_resource_action_resource_upgrade_test.go, internal/services/azapi_resource_list_data_source_test.go, internal/services/azapi_resource_test.go, internal/services/azapi_resource_upgrade_test.go, internal/services/azapi_update_resource_test.go
This PR removes azurerm usage from the test cases to speed up the end to end tests. Because downloading external providers in each test case takes too long.
This reduces the time from 200 mins to 90 mins.
=> remove azurerm provider from testcases

CHANGELOG.md, internal/services/common.go, internal/services/migration/azapi_data_plane_resource_migration_v0_to_v2.go, internal/services/migration/azapi_data_plane_resource_migration_v1_to_v2.go, internal/services/migration/azapi_resource_action_migration_v0_to_v2.go, internal/services/migration/azapi_resource_action_migration_v1_to_v2.go, internal/services/migration/azapi_resource_migration_v0_to_v2.go, internal/services/migration/azapi_resource_migration_v1_to_v2.go, internal/services/migration/azapi_update_resource_migration_v0_to_v2.go, internal/services/migration/azapi_update_resource_migration_v1_to_v2.go
This PR fixes the state migration for `response_export_values`. Previously, the null list will be converted to a dynamic value whose underlying value is a null list. If the user doesn't specify the `response_export_values`, the config value should be a null dynamic value, and this will cause a plan diff because the structs are different.
=> bugfix: fix state migration for `response_export_values`

.azdo/ado-oidc-pipeline.yml, .github/workflows/acc-test.yaml, CHANGELOG.md, docs/guides/service_principal_oidc.md, docs/index.md, internal/provider/provider.go, templates/guides/service_principal_oidc.md
This PR adds support for azure pipeline credential
related issue: https://github.com/Azure/terraform-provider-azapi/issues/515, https://github.com/Azure/terraform-provider-azapi/issues/414
test results from azure pipelines
test results from GitHub actions
=> support azure pipeline credential

CHANGELOG.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_test.go
This PR updates the logic that parse the dynamic value, previously it uses the "String()" method to get the JSON string, but this method is used to get a human-readable string for logging, and it can't guarantee it'll always be JSON and backward compatible.
=> `replace_triggers_refs` should use `dynamic.ToJson` to parse the dynamic value

docs/guides/2.0-upgrade-guide.md, internal/services/azapi_resource.go, internal/services/azapi_resource_preflight_test.go, internal/services/preflight/preflight.go, templates/guides/2.0-upgrade-guide.md
This PR adds identity to the preflight request body, without which the aks cluster's preflight will fail because it requires one of managed identity and service principal profile to be set.
I also added a test for aks preflight to guarantee that.
=> bugfix: preflight request doesn not include identity

internal/clients/resource_client.go, internal/services/azapi_resource_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/575
When running this case in the azure pipeline, it will throws 401 instead of 403 when running locally, and 401 error will be wrapped as a NonRetriableError. This PR unwraps the error.
=> unwrap NonRetriableError

internal/clients/data_plane_client.go, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/common.go
https://github.com/Azure/terraform-provider-azapi/pull/621 introduces logics that retry the GET 404 after PUT is successful.
This PR sets the maximum total time for retries. Because I found a case that the resource might not be successfully created, and the GET requests keeps failing.
=> avoid infinite retry

CHANGELOG.md, docs/index.md, internal/features/user_flags.go, internal/provider/provider.go, internal/services/azapi_resource.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_update_resource.go
This PR adds a provider feature flag `disable_default_output` which is used to disable the default behavior that output the read only properties.
=> `azapi`: Support `disable_default_output` field

CHANGELOG.md, internal/services/dynamic/dynamic.go
related issue: https://github.com/Azure/terraform-provider-azapi/issues/538#issuecomment-2426940037
When the `body` contains an unknown float number, the provider will crash.
For example: 
```
resource "azapi_resource" "automationAccount1" {
type      = "Microsoft.Automation/automationAccounts@2023-11-01"
parent_id = azapi_resource.resourceGroup.id
name      = "acctesthenglu021"
location  = "westus"
body = {
properties = {
sku = {
name = "Basic"
value = azapi_resource.automationAccount.output.properties.sku.name == "Basic" ? 1.1 : 1.2
}
}
}
schema_validation_enabled = false
response_export_values = []
}
```
=> bugfix: provider crash if body contains unknown float value

internal/clients/account.go
fix crash similar to https://github.com/Azure/terraform-provider-azapi/issues/566 but for tenant ID:
```
Stack trace from the terraform-provider-azapi_v2.0.1 plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x89b799]
goroutine 36 [running]:
github.com/Azure/terraform-provider-azapi/internal/clients.(*ResourceManagerAccount).GetTenantId(0xc000220e50)
github.com/Azure/terraform-provider-azapi/internal/clients/account.go:44 +0x139
github.com/Azure/terraform-provider-azapi/internal/services.(*ClientConfigDataSource).Read(0xc001a00018, {0xfacafb8, 0xc001837620}, {{{{0xfad0460, 0xc001837da0}, {0xd2d140, 0xc001837d10}}, {0xfad3040, 0xc001882640}}, {{{0x0, ...}, ...}, ...}, ...}, ...) …
```
=> Fix the crash that occurs when no tenant ID is configured in Azure CLI

examples/Microsoft.Network_networkManagers_ipamPools@2024-01-01-preview/main.tf, examples/Microsoft.Network_networkManagers_ipamPools_staticCidr@2024-01-01-preview/main.tf, examples/Microsoft.Network_networkManagers_verifierWorkspace@2024-01-01-preview/main.tf, examples/Microsoft.Network_networkManagers_verifierWorkspace_reachabilityAnalysisIntent@2024-01-01-preview/main.tf, examples/Microsoft.Network_networkManagers_verifierWorkspace_reachabilityAnalysisIntent_reachabilityAnalysisRun@2024-01-01-preview/main.tf, examples/Microsoft.VoiceServices_communicationsGateways_testLines@2023-01-31/main.tf
This PR adds examples for the below resource types:
- Microsoft.Network/networkManagers/ipamPools
- Microsoft.Network/networkManagers/ipamPools/staticCidr
- Microsoft.Network/networkManagers/verifierWorkspace
- Microsoft.Network/networkManagers/verifierWorkspace/reachabilityAnalysisIntent
- Microsoft.Network/networkManagers/verifierWorkspace/reachabilityAnalysisIntent/reachabilityAnalysisRun
Tests:
```bash
=== RUN   TestAccExamples
--- PASS: TestAccExamples (0.00s)
=== RUN   TestAccExamples/0-Microsoft.Network_networkManagers_ipamPools@2024-01-01-preview
azapi_resource_example_test.go:23: Running example ../../examples/0-Microsoft.Network_networkManagers_ipamPools@2024-01-01-preview
=== PAUSE TestAccExamples/0-Microsoft.Network_networkManagers_ipamPools@2024-01-01-preview
=== CONT …
```
=> add example for `Microsoft.Network/networkManagers`'s nested resources

CHANGELOG.md, internal/clients/account.go, internal/clients/client.go, internal/services/azapi_client_config_data_source.go
Previously the resource manager account is initialized incorrectly, because it uses the same structure to initialize the resource manager.
This PR fixes above bug and abstracts the object ID lazy load function to an interface to simplify the implementation.
=> bugfix: resource manager account is not initialized correctly

CHANGELOG.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_test.go, internal/services/azapi_update_resource.go
Fixes https://github.com/Azure/terraform-provider-azapi/issues/672
=> bugfix: ordering locks to avoid deadlock

internal/clients/data_plane_client.go, internal/clients/resource_client.go, internal/retry/retryable_errors.go, internal/services/azapi_client_config_data_source.go, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_update_resource.go, internal/services/common.go
As per internal thread:
- Improved 403 handling for MG resources to include child resources
- Fix bug in get after put retry timeout so the environment variable works properly
- Added debug output to retry
I could also pass the regex to the get after put retry, but since the body is nil then the retry func catches the issue where we get a 403. WDYT @ms-henglu
=> fix: improve retry behavior with resources at MG scope

docs/guides/service_principal_client_certificate.md, templates/guides/service_principal_client_certificate.md
fixes https://github.com/Azure/terraform-provider-azapi/issues/609
The parse certificate function provided by azure track 2 SDK has limitations, this PR adds them in the docs.
refs: https://github.com/Azure/azure-sdk-for-go/issues/22906#issuecomment-2121458876
=> clarify client certificate authentication limitation

docs/data-sources/resource.md, internal/services/azapi_resource_data_source.go
Tests:
```
data "azapi_resource" "rg" {
type = "Microsoft.Resources/resourceGroups@2024-03-01"
name = "myRG"
}
data "azapi_resource" "subscription" {
type = "Microsoft.Resources/subscriptions@2024-03-01"
}
data "azapi_resource" "vnet" {
type      = "Microsoft.Network/virtualNetworks@2024-03-01"
name      = "myVnet"
parent_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG"
}
data "azapi_resource" "vnet2" {
type        = "Microsoft.Network/virtualNetworks@2024-03-01"
resource_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/myRG/providers/Microsoft.Network/virtualNetworks/myVnet"
}
```
=> improve validation for azapi_resource data source

CHANGELOG.md, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_ephemeral.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_update_resource.go, internal/services/resource.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/711
=> bugfix: query parameters and headers don't work properly with unknown values

CHANGELOG.md, internal/services/common.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/724
=> bugfix: remove volatile fields from the default output

internal/clients/data_plane_client_test.go, internal/clients/resource_client.go, internal/clients/resource_client_test.go, internal/retry/retryable_errors.go, internal/services/azapi_data_plane_resource.go, internal/services/azapi_resource.go, internal/services/azapi_resource_action_data_source.go, internal/services/azapi_resource_action_ephemeral.go, internal/services/azapi_resource_action_resource.go, internal/services/azapi_resource_data_source.go, internal/services/azapi_resource_list_data_source.go, internal/services/azapi_update_resource.go
@jaredfholgate discovered an issue with long resource operations and retry.
The package we use has a [default max elapsed time of 15m](https://github.com/cenkalti/backoff/blob/720b78985a65c0452fd37bb155c7cac4157a7c45/exponential.go#L83).
This causes an issue when the resource's `timeout` values were set to longer than 15m.
This PR adds the `backoff.WithMaxElapsedTime()` setting into the retry configuration. It sets this to the resource's timeout value. Since we use the context aware retry function in the backoff package this value just needs to be equal to or higher than the timeout value. Once the context deadline is exceeded then the retry package will exit anyway (we already have unit tests for this).
I have also refactored to remove the unnecessary `NewRetryableErrors()` function from …
=> fix(retry): add WithMaxElapsedTime to retry options and refactor to use functional options

CHANGELOG.md, internal/services/azapi_resource.go, internal/services/parse/azurerm_resource_id.go, internal/services/parse/azurerm_resource_id_test.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/704
=> bugfix: format azurerm resource ID when move resource

CHANGELOG.md, internal/services/migration/azapi_resource_migration_v1_to_v2.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/801
=> bugfix: `azapi_resource_action` migration failed if body is empty string

examples/Qumulo.Storage_fileSystems@2024-06-19/main.tf
The test needs to be run in a subscription associated with [valid payment method](https://learn.microsoft.com/en-us/azure/partner-solutions/qumulo/troubleshoot#purchase-errors), in my case the test is run in a Resource Group provided by the service team:
Due to payment limitation, maybe we can skip this in daily test
=> add example for qumulo storage

internal/services/azapi_resource.go
@ms-henglu
Please see this small fix that was missed on the last update to the retry code.
This fixes the Delete() method of azapi_resource and brings it in line with the other CRUD methods. This fix ensures that the retry client has the correct max elapsed time, rahter than the default of 15 minutes.
=> fix(azapi_resource): set context deadline before config retry

CHANGELOG.md, internal/services/azapi_resource.go, internal/services/azapi_resource_test.go
After moving resource, `azapi` sets the private data to indicate the resource is moved from `azurerm` provider, but in the read func, this flag is not removed. This will cause the resource could not be updated correctly.
This PR fixes this bug and adds a test case for it.
=> bugfix: `azapi_resource` cannot be updated correctly after moving from `azurerm` provider

internal/services/ephemeral_body_private.go, internal/services/migration/azapi_resource_migration_v0_to_v2.go, internal/services/migration/azapi_resource_migration_v1_to_v2.go, internal/services/migration/azapi_update_resource_migration_v0_to_v2.go, internal/services/migration/azapi_update_resource_migration_v1_to_v2.go
This PR fixes the state migration because a `sensitive_body` field is recently added.
=> Branch 240428 fix sensitive body migration

internal/services/myplanmodifier/planmodifierdynamic/dynamic_requires_replace.go, internal/services/myplanmodifier/planmodifierdynamic/dynamic_requires_replace_test.go
fixes importing resource with replace_triggers_external_values recreates the resource #858
=> fix(planmodifier): requires replace external values should not replace if state value is null

CHANGELOG.md, internal/services/azapi_update_resource_test.go, utils/json.go, utils/json_test.go
This PR updates the logic that `azapi_update_resource` uses item's identifier "name" to match with the correct item in an array.
=> bugfix: `azapi_update_resource` does not update the correct item in an array

docs/resources/Microsoft.StandbyPool_standbyContainerGroupPools.md, docs/resources/Microsoft.StandbyPool_standbyvirtualmachinepools.md, examples/Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01/basic/README.md, examples/Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01/basic/main.tf, examples/Microsoft.StandbyPool_standbyvirtualmachinepools@2025-03-01/basic/main.tf, tools/generator-example-doc/resource_types.json
I did not find example of `README.md` of examples... But this example needs set up permission in advance..
test:
```
❯ make example-test TARGET=Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01
TF_ACC=1 ARM_TEST_EXAMPLES=Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01 go test -v ./internal/services/... -run TestAccExamples_Selected -timeout 300m -ldflags="-X=github.com/Azure/terraform-provider-azapi/version.ProviderVersion=acc"
=== RUN   TestAccExamples_Selected
azapi_resource_example_test.go:56: Found 1 testcases
=== RUN   TestAccExamples_Selected/../../examples/Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01/basic/main.tf
=== PAUSE TestAccExamples_Selected/../../examples/Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01/basic/main.tf
=== CONT …
```
=> example - `Microsoft.StandbyPool_standbyContainerGroupPools@2025-03-01`

internal/provider/provider.go
The log's writer is redirected by the underlying go-plugin, hence we shall continue using that other than output to stderr, otherwise the log will be messy..
=> Print entrauth logs to the same redirected writer instead of stderr

internal/services/azapi_resource_preflight_test.go, internal/services/preflight/preflight.go, internal/services/preflight/preflight_test.go
Fixed the name field to align with the number of segments in the resource type field. For example, if the type is "virtualNetworks/subnets", the name will now be "vnetName/subnetName".
=> preflight - fix name field

internal/clients/options.go, internal/clients/resource_client.go
Fixes #968
Hi @ms-henglu
AzAPI v2.5.0 introduced a regression in the retry logic that is causing issues with Azure Landing Zones deployments (we rely heavily on this feature).
The reason for the regression was the move from dedicated retry logic to using the SDK's ShouldRetry func. The adoption of ShouldRetry overrides the use of StatusCodes as a retry test.
This PR moves the status code checks into the ShouldRetry funcs so that they are always checked.
In #970 I propose that we deprecate the [maximum_busy_retry_attempts](https://registry.terraform.io/providers/Azure/azapi/latest/docs#maximum_busy_retry_attempts-1) provider configuration and set this to `math.MaxInt16`. This move will simplify the provider configuration for callers and also revert to the context deadline, as it should.
=> fix: retry regression in 2.5.0

CHANGELOG.md, internal/clients/account.go
fixes https://github.com/Azure/terraform-provider-azapi/issues/963
fixes https://github.com/Azure/terraform-provider-azapi/issues/981
When use Azure CLI authentication and specify a subscription ID in the `azapi` provider block, the specified subscription ID will be overridden by the subscription ID read from azure cli.
=> bugfix: specified subscription ID should not be overridden by Azure CLI default subscription ID
